### ISSUE TITLE
Pretty option and no-flow files not working together it seems :)

### ISSUE THREAD

**Issue by katywings** [flowtype/flow-remove-types#26]
I get the following error when I use flow-remove-types pretty option with files which arent under "flow":

```
Error transforming /home/katja/Dokumente/alo/node_modules/lodash/cloneDeep.js with 'flow-remove-types' plugin: Cannot read property 'length' of undefined
TypeError: Error transforming /home/katja/Dokumente/alo/node_modules/lodash/cloneDeep.js with 'flow-remove-types' plugin: Cannot read property 'length' of undefined
    at generateSourceMappings (/home/katja/Dokumente/alo/node_modules/flow-remove-types/index.js:287:35)
    at Object.generateMap (/home/katja/Dokumente/alo/node_modules/flow-remove-types/index.js:116:28)
    at Object.transform (/home/katja/Dokumente/alo/node_modules/rollup-plugin-flow/index.js:15:28)
    at /home/katja/.nvm/versions/node/v4.4.5/lib/node_modules/rollup/src/utils/transform.js:19:35
```

It seems the problem might be in the following code sequence:

At https://github.com/flowtype/flow-remove-types/blob/master/index.js#L40
```js
    if (pragmaStart === -1 && !all) {
      return resultPrinter(options, source);
    }
```

At https://github.com/flowtype/flow-remove-types/blob/master/index.js#L111
```js
    generateMap: function () {
      return {
        version: 3,
        sources: [ 'source.js' ],
        names: [],
        mappings: pretty ? generateSourceMappings(removedNodes) : ''
      };
    }
```

At https://github.com/flowtype/flow-remove-types/blob/master/index.js#L281
```js

// Generate a source map when *removing* nodes rather than replacing them
// with spaces.
function generateSourceMappings(removedNodes) {
  var mappings = '';
  var end = { line: 1, column: 0 };

  for (var i = 0; i < removedNodes.length; i++) {
```

If you would have used flow this wouldnt had happened xDD

**Comment by StreetStrider** [comment]
Have the same issue. I got my code successfully bundled if pretty is disabled. That means the code is well-formed. Then I turn `pretty: true`:
```
Error transforming …/mod.js with 'flow-remove-types' plugin: Cannot read property 'length' of undefined
…
     code: 'BAD_TRANSFORMER',
     plugin: 'flow-remove-types',
```

**Comment by leebyron** [comment]
Thanks for the report

**Comment by StreetStrider** [comment]
@leebyron, great, thank you 👍

**Comment by katywings** [comment]
@leebyron Yeah thanks! <3
