### ISSUE TITLE
Flow-node chokes on async/await-syntax

### ISSUE THREAD

**Issue by benwixen** [flowtype/flow-remove-types#35]
If you're using async/await-syntax on NodeJS (available with a flag, and by default from NodeJS 8), the flow-node process chokes on invalid syntax.

It would be nice to support this, not to force people over to Babel.

**Comment by leebyron** [comment]
I'm adding a test case to illustrate that async/await works ok.

Not sure how you encountered this - please let me know if there's a corner-case that flow-node isn't supporting, perhaps related to #37?

**Comment by ssrballin** [comment]
Hey, not sure if this is a related issue, but I'm also having trouble building when using await.

Here is my output:

```
> flow-remove-types src/ -d lib/

src/index.js
 ↳ Syntax Error: await is a reserved word (15:17)
   14:    const result = await db.account.usernameExists(req.body.username)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! downtohang-mobileapi@0.0.0 build: `flow-remove-types src/ -d lib/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the downtohang-mobileapi@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saadsiddiqui/.npm/_logs/2017-06-16T19_50_26_141Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! downtohang-mobileapi@0.0.0 start: `npm run build && node lib/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the downtohang-mobileapi@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saadsiddiqui/.npm/_logs/2017-06-16T19_50_26_170Z-debug.log

Process finished with exit code 1
```

Also here are the contents of `/Users/saadsiddiqui/.npm/_logs/2017-06-16T19_50_26_141Z-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle downtohang-mobileapi@0.0.0~prebuild: downtohang-mobileapi@0.0.0
6 silly lifecycle downtohang-mobileapi@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle downtohang-mobileapi@0.0.0~build: downtohang-mobileapi@0.0.0
8 verbose lifecycle downtohang-mobileapi@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle downtohang-mobileapi@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/saadsiddiqui/Desktop/downtohang/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/saadsiddiqui/Desktop/downtohang/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle downtohang-mobileapi@0.0.0~build: CWD: /Users/saadsiddiqui/Desktop/downtohang
11 silly lifecycle downtohang-mobileapi@0.0.0~build: Args: [ '-c', 'flow-remove-types src/ -d lib/' ]
12 silly lifecycle downtohang-mobileapi@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle downtohang-mobileapi@0.0.0~build: Failed to exec build script
14 verbose stack Error: downtohang-mobileapi@0.0.0 build: `flow-remove-types src/ -d lib/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid downtohang-mobileapi@0.0.0
16 verbose cwd /Users/saadsiddiqui/Desktop/downtohang
17 verbose Darwin 16.6.0
18 verbose argv "/usr/local/Cellar/node/8.1.0_1/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.1.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error downtohang-mobileapi@0.0.0 build: `flow-remove-types src/ -d lib/`
23 error Exit status 1
24 error Failed at the downtohang-mobileapi@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Please let me know if you would like any other relevant info.

Any help would be greatly appreciated! Thanks in advance! 🙂
