### ISSUE TITLE
flow-node fails on arguments passed to node executable

### ISSUE THREAD

**Issue by jordansexton** [flowtype/flow-remove-types#37]
```shell
flow-node --debug-brk=62295 script.js
module.js:472
    throw err;
    ^

Error: Cannot find module '--debug-brk=62295'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/jordan/flow-node-bug/node_modules/flow-remove-types/flow-node:103:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by jordansexton** [comment]
My workaround:

```javascript
#!/usr/bin/env node
'use strict';

require('flow-remove-types/register');

const argv = process.argv;
const args = [];
for (let i = 2, length = argv.length; i < length; i++) {
    args.push(argv[i]);
}

const path   = require('path');
const source = path.resolve(process.cwd(), args[0]);

args.unshift(argv[0]);

process.execArgv = argv;
process.argv     = args;

require(source);
```

**Comment by faizalpribadi** [comment]
@annotation flow-node REPL issues: 
```js
$ flow-node
  var x: number = 'string'
  undefined
  x
  'string'
```
not throwing error exception like flow repl error, please explain :)

**Comment by caseyduquettesc** [comment]
And if you're looking to use the above solution to debug flow code in VS Code,

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/flow.js",
            "args": [
              "${workspaceRoot}/bin/script.js"
            ]
        }
    ]
}
```

**Comment by leebyron** [comment]
Ideally flow-node would pass through arguments, open to PRs adding this

**Comment by leebyron** [comment]
Fixed in the new release!

**Comment by jordansexton** [comment]
Awesome. Thanks!
