### ISSUE TITLE
Failing to run on Windows

### ISSUE THREAD

**Issue by barendb** [flowtype/flow-remove-types#45]
Having some trouble running this on Windows 😭  (Azure Site)
Works perfectly fine on my Mac/Linux

Version: 1.2.1

```
D:\home\site\repository\node_modules\.bin\flow-remove-types:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.10.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.10.10\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! abc@1.0.0 build: `rm -rf dist && node node_modules/.bin/flow-remove-types -p -m -d dist src`
npm ERR! Exit status 1
....
```

**Comment by leebyron** [comment]
This looks like you may need something like [cross-env](https://www.npmjs.com/package/cross-env)
